<Project>
  <PropertyGroup>
    <Version>0.3.0-rc6</Version>
    <AssemblyVersion>0.3.0.0</AssemblyVersion>
    <FileVersion>0.3.0.6</FileVersion>
    <InformationalVersion>0.3.0-rc6+choirlauncher-rc6-20260730.1</InformationalVersion>
    <Product>ChoirLauncher</Product>
    <Company>Henrique</Company>
    <Authors>Henrique</Authors>
    <Copyright>Copyright © Henrique 2026</Copyright>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
</Project>
